# Generated by Django 3.1.7 on 2021-03-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('score', models.PositiveIntegerField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('deadline', models.DateField()),
                ('suggestions', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
    ]
