# Generated by Django 3.1.7 on 2021-03-03 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='singhealth.staff'),
        ),
    ]
