# Generated by Django 3.1.7 on 2021-03-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0003_complaint_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F & B', 'F & B'), ('Others', 'Others')], max_length=100, null=True)),
                ('location', models.CharField(choices=[('West', 'West'), ('East', 'East'), ('North', 'North'), ('South', 'South')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='singhealth.outlet')),
            ],
        ),
    ]
