# Generated by Django 3.1.7 on 2021-03-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0005_auto_20210303_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='singhealth.tenant'),
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
