# Generated by Django 3.1.7 on 2021-03-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0006_auto_20210304_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
