# Generated by Django 3.1.7 on 2021-03-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0007_complaint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='deadline',
            field=models.DateField(help_text='YYYY-MM-DD', null=True),
        ),
    ]
