# Generated by Django 3.1.7 on 2021-03-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0008_auto_20210304_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(default='Unknown', max_length=100, null=True),
        ),
    ]
