# Generated by Django 3.1.7 on 2021-03-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0010_auto_20210305_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
