# Generated by Django 3.1.7 on 2021-03-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0012_auto_20210305_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
