# Generated by Django 3.1.7 on 2021-03-05 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0013_auto_20210305_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='tenant_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='complaint',
            name='tenant_response',
            field=models.TextField(default='Pending response', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
