# Generated by Django 3.1.7 on 2021-03-05 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0014_auto_20210305_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 5), null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='tenant_response',
            field=models.TextField(default='Tenant has not yet given a response', null=True),
        ),
    ]
