# Generated by Django 3.1.7 on 2021-03-05 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0015_auto_20210305_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
