# Generated by Django 3.1.7 on 2021-03-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0016_auto_20210305_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
