# Generated by Django 3.1.7 on 2021-03-05 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0019_auto_20210305_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
