# Generated by Django 3.1.7 on 2021-03-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0020_auto_20210305_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='notes',
            field=models.TextField(help_text='Not visible to tenant', null=True),
        ),
    ]
