# Generated by Django 3.1.7 on 2021-03-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0022_auto_20210305_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='tenant_response',
            field=models.TextField(default='Pending response', null=True),
        ),
    ]
