# Generated by Django 3.1.7 on 2021-03-09 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0023_auto_20210305_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='suggestions',
            field=models.TextField(help_text='**Shown to tenant', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='tenant_response',
            field=models.TextField(default='', null=True),
        ),
    ]
