# Generated by Django 3.1.7 on 2021-03-09 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0025_auto_20210309_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='title',
            new_name='subject',
        ),
    ]
