# Generated by Django 3.1.7 on 2021-03-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0026_auto_20210309_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending Tenant Response', 'Pending Tenant Response'), ('Pending Staff Response', 'Pending Staff Response')], max_length=100, null=True),
        ),
    ]
