# Generated by Django 3.1.7 on 2021-03-12 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0028_auto_20210309_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='tenant_picture',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='tenant_response',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='singhealth.staff'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Expired', 'Expired'), ('Resolved', 'Resolved')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='singhealth.tenant'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='singhealth.outlet'),
        ),
        migrations.CreateModel(
            name='Edit_Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('comments', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('edit_name', models.CharField(max_length=100, null=True)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='singhealth.complaint')),
            ],
        ),
    ]
