# Generated by Django 3.1.7 on 2021-03-12 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0029_auto_20210312_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
