# Generated by Django 3.1.7 on 2021-03-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0031_auto_20210312_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
