# Generated by Django 3.1.7 on 2021-03-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0035_auto_20210317_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='score',
        ),
    ]
