# Generated by Django 3.1.7 on 2021-03-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0037_auto_20210324_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Editing', 'Editing'), ('Open', 'Open'), ('Expired', 'Expired'), ('Resolved', 'Resolved')], max_length=100, null=True),
        ),
    ]
