# Generated by Django 3.1.7 on 2021-03-25 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0040_auto_20210325_1535'),
        ('singhealth', '0038_auto_20210325_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checklist.checklistscore'),
        ),
    ]
