# Generated by Django 3.1.7 on 2021-03-25 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('singhealth', '0039_complaint_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_complaint', to=settings.AUTH_USER_MODEL),
        ),
    ]
