# Generated by Django 3.1.7 on 2021-04-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0040_auto_20210325_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Expired', 'Expired'), ('Resolved', 'Resolved')], max_length=100, null=True),
        ),
    ]
