# Generated by Django 3.0.7 on 2021-03-26 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0052_auto_20210326_1112'),
        ('singhealth', '0040_auto_20210325_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checklist.ChecklistScore'),
        ),
    ]
