# Generated by Django 3.0.7 on 2021-03-29 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0054_auto_20210330_0143'),
        ('singhealth', '0042_auto_20210326_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checklist.ChecklistScore'),
        ),
    ]
