# Generated by Django 3.0.7 on 2021-04-05 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0063_auto_20210405_1552'),
        ('singhealth', '0042_auto_20210405_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checklist.ChecklistScore'),
        ),
    ]
