# Generated by Django 3.0.7 on 2021-04-07 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0065_auto_20210407_1853'),
        ('singhealth', '0044_auto_20210405_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checklist.ChecklistScore'),
        ),
    ]
