# Generated by Django 3.2 on 2021-04-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0045_auto_20210407_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outlet',
        ),
    ]
