# Generated by Django 3.2 on 2021-04-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhealth', '0046_delete_outlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F & B', 'F & B'), ('Others', 'Others')], max_length=100, null=True)),
                ('location', models.CharField(choices=[('West', 'West'), ('East', 'East'), ('North', 'North'), ('South', 'South')], max_length=100, null=True)),
            ],
        ),
    ]
