@startuml

alt Invalid login credentials
    Staff -> Application : Invalid_logincredentials()
    Application -> Backend : check_logincredentials()
    activate Backend
        Backend -> Backend : check_logincredentials()
        Backend -> Application : invalid_credentials() 
    deactivate Backend
    Application --> Staff : invalid_login_prompt()
else Successful login
    Staff -> Application : Login()
    Application --> Staff : Staff_home()
end


Staff -> Application : checklist_additem()
Application -> Application : update_checklistitems()


Staff -> Application : create_audit()
Application -> Application : update_auditlist()
Staff -> Application : export_audit_excelsheet()
Application -> Backend : create_excelsheet_audit()
Backend -> Application : return_excelsheet_audit()
Application --> Staff : download_excelsheet_audit()


alt Valid email form fields submission
    Staff -> Application : export_email()
    Application -> Backend : send_email()
    Backend --> Staff : email_exported()
else Invalid email form fields submission (Missing form fields/wrong format)
    Staff -> Application : invalid_export_email()
    Application --> Staff : prompt_invalid_email_form()
end


alt Successful complaint creation
    Staff -> Application : create_complaint()
    Application -> Application : update_complaintlist()
else Invalid complaint creation (Missing form fields/wrong format)
    Staff -> Application : create_invalid_complaint()
    Application --> Staff : prompt_invalid_complaintlist_form()
end


loop Daily
    Application --> Tenant : emailnotify_unresolvedcomplaints()
end


alt Invalid login credentials
    Tenant -> Application : Invalid_logincredentials()
    Application -> Backend : check_logincredentials()
    activate Backend
        Backend -> Backend : check_logincredentials()
        Backend -> Application : invalid_credentials() 
    deactivate Backend
    Application --> Tenant : invalid_login_prompt()
else Successful login
    Tenant -> Application : Login()
    Application --> Tenant : Tenant_home()
end

Tenant -> Application : viewcomplaints()
Application --> Tenant : complaintlist()
Tenant -> Application : click_viewreport()

alt Complaint is resolved
    Application --> Tenant : viewonly_complaint()

else Complaint is open, unresolved
    loop While Open Complaint

        loop Tenant has updates

            alt Invalid rectification attempt (Missing form fields/wrong format)
                Tenant -> Application : upload_invalid_rectification()
                Application --> Tenant : prompt_invalid_rectification()

            else Successful rectification upload 
                Tenant -> Application : upload_rectification()
                Application -> Application : update_tenantrectificationlist()
            end
        end

        loop Daily
        Application --> Staff : rectification_update_emailnotify()
        end

    end

    alt Rectification passable
        Staff -> Application : Resolve_complaintreport()
        Application -> Tenant : resolved_complaint_emailnotify()
    else Failed compliance check again
        Staff -> Application : Resolve_complaint()
        Application -> Application : update_complaint_resolved()
        Staff -> Application : create_complaint()
    end

else Complaint deadline expired
    loop Daily, until updated complaint
        Application --> Staff : emailnotify_expiredcomplaint()
    end
end

Staff -> Application : Logout()
Application --> Staff : Loginpage()

Tenant -> Application : Logout()
Application --> Tenant : Loginpage()

@enduml
