# Generated by Django 3.1.7 on 2021-03-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='tick',
            field=models.BooleanField(verbose_name='Safety'),
        ),
    ]
