# Generated by Django 3.1.7 on 2021-03-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20210313_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='tick',
            field=models.BooleanField(blank=True, verbose_name='Safety'),
        ),
    ]
