# Generated by Django 3.1.7 on 2021-03-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20210313_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='form',
        ),
    ]
