# Generated by Django 3.1.7 on 2021-03-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_auto_20210314_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckListForm',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='tick',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='box',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='requirements',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='type',
            field=models.CharField(choices=[('F&B', 'F&B'), ('Others', 'Others')], max_length=10, null=True),
        ),
    ]
