# Generated by Django 3.1.7 on 2021-03-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_auto_20210314_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='box',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
    ]
