# Generated by Django 3.1.7 on 2021-03-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_auto_20210321_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='items',
            field=models.ManyToManyField(to='checklist.CheckListItem'),
        ),
        migrations.AlterField(
            model_name='checklistscore',
            name='unchecked',
            field=models.ManyToManyField(to='checklist.CheckListItem'),
        ),
    ]
