# Generated by Django 3.1.7 on 2021-03-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_auto_20210321_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='category',
            field=models.CharField(choices=[('F&B', 'F&B'), ('Non F&B', 'Non F&B')], default='no category', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='description',
            field=models.CharField(default='no description', max_length=200, null=True),
        ),
    ]
