# Generated by Django 3.1.7 on 2021-03-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0027_auto_20210322_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='category',
            field=models.CharField(choices=[('fnb', 'fnb'), ('nonfnb', 'nonfnb')], default='no category', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='items',
            field=models.ManyToManyField(to='checklist.ChecklistItem'),
        ),
        migrations.AlterField(
            model_name='checklistscore',
            name='checked',
            field=models.ManyToManyField(to='checklist.ChecklistItem'),
        ),
    ]
