# Generated by Django 3.1.7 on 2021-03-25 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0044_auto_20210325_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='items',
            field=models.ManyToManyField(related_name='checklist', to='checklist.ChecklistItem'),
        ),
        migrations.AlterField(
            model_name='checklistscore',
            name='checked',
            field=models.ManyToManyField(related_name='checked', to='checklist.ChecklistItem'),
        ),
        migrations.AlterField(
            model_name='checklistscore',
            name='tenant',
            field=models.ForeignKey(default='tenant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_checklist', to=settings.AUTH_USER_MODEL),
        ),
    ]
