# Generated by Django 3.1.7 on 2021-03-25 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0045_auto_20210325_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistscore',
            name='unchecked',
            field=picklefield.fields.PickledObjectField(default={}, editable=False),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='items',
            field=models.ManyToManyField(related_name='checklist', to='checklist.ChecklistItem'),
        ),
        migrations.RemoveField(
            model_name='checklistscore',
            name='checked',
        ),
        migrations.AddField(
            model_name='checklistscore',
            name='checked',
            field=picklefield.fields.PickledObjectField(default={}, editable=False),
        ),
        migrations.AlterField(
            model_name='checklistscore',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_checklist', to=settings.AUTH_USER_MODEL),
        ),
    ]
