# Generated by Django 3.1.7 on 2021-03-25 16:10

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0047_auto_20210326_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='items',
            field=models.ManyToManyField(related_name='checklist', to='checklist.ChecklistItem'),
        ),
        migrations.AlterField(
            model_name='checklistscore',
            name='checked',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='checklistscore',
            name='unchecked',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
    ]
