# Generated by Django 3.1.7 on 2021-04-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0051_auto_20210326_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='items',
            field=models.ManyToManyField(related_name='checklist', to='checklist.ChecklistItem'),
        ),
    ]
