# Generated by Django 3.0.7 on 2021-03-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0052_auto_20210326_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='items',
            field=models.ManyToManyField(related_name='checklist', to='checklist.ChecklistItem'),
        ),
    ]
