# Generated by Django 3.2 on 2021-04-12 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0066_alter_checklist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='items',
            field=models.ManyToManyField(related_name='checklist', to='checklist.ChecklistItem'),
        ),
        migrations.AlterField(
            model_name='checklistscore',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
