# Generated by Django 3.2 on 2021-04-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0073_alter_checklist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='items',
            field=models.ManyToManyField(related_name='checklist', to='checklist.ChecklistItem'),
        ),
    ]
