# Generated by Django 3.0.7 on 2021-03-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tenants',
            new_name='Tenant',
        ),
    ]
